### ISSUE TITLE
请在文档中注明不支持Excel97-2003

### ISSUE THREAD

**Issue by kw13202** [xin-lai/Magicodes.IE#11]
using (var excelPackage = new ExcelPackage(stream))
这行代码读取xls的Excel时，Sheet的数量为0，后续报错无法操作，将文档格式改为xlsx后，此问题消失

**Comment by xin-lai** [comment]
收到，这是EPPlus的问题。可以考虑转换格式后再导入。

**Comment by sgf** [comment]
> 
> 
> 收到，这是EPPlus的问题。可以考虑转换格式后再导入。

日后有计划考虑 2003的么，哪怕是基础级别的支持。感觉缺了2003额支持，有一种不完整的感觉。

**Comment by xin-lai** [comment]
@sgf 要看后续的精力了，目前3.0没有考虑这块。

**Comment by sgf** [comment]
> @sgf 要看后续的精力了，目前3.0没有考虑这块。

嗯，主要是 EPPlus 不支持2003 格式 😂

**Comment by xin-lai** [comment]
@sgf 这个倒是不是主要的问题，EPPlus我们维护了一个版本。主要的问题是，目前整个项目只有我和 @hueifeng 是活跃的，精力非常有限。
