### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by FeynmanLoo** [xin-lai/Magicodes.IE#7]
在使用导出excel功能的时候，刚开始导出，内存猛的上涨接近100M，导出结束后下降80+M，实际导出的excel才5M，随着不断重复这个导出操作，应用内存逐渐上升，几乎没结束一次导出，内存占用就多20M，请问有遇到这个问题吗？如何解决？

**Comment by xin-lai** [comment]
导出数据量多大？能否贴下代码。

**Comment by xin-lai** [comment]
我测试导出百万数据没有报错，不过内存高峰是94M。单数据对象40M左右。
